name: My Panda CI
on:
  push:
    branches: [main]

jobs:
  builds:
    runs-on: ubuntu-latest
    name: My Panda CI
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v5.2.0
        with:
          go-version: 1.17.0
      - name: what is go version
        run: |
          go version
          ls
          go test
      - name: Checkout private repo remotely
        uses: actions/checkout@v4
        with:
          repository: chan-andy/go_assignment
          path: cmd
          token: ${{ secrets.TEST_SECRET2 }}

      - name: List out hidden files
        run: |
          ls
          cd cmd
          ls
      - uses: discord-actions/message@v2
        with:
    # A Discord webhook URL
          webhookUrl:  https://discordapp.com/api/webhooks/1316956354786885673/TnLUfOQiSbcjinGjEXP44tQwVosbe8HGv_gviHMyIZYWbWlr4rcTYRDpNk24h2DO7pa5
          message: "TEST"
          username: "andy"
